import { tokens } from "@/lib/theme";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <style>{`:root { --theme-background: ${tokens.colors.surface}; --theme-foreground: ${tokens.colors.text}; } @media (prefers-color-scheme: dark) { :root { --theme-background: ${tokens.colors.background}; --theme-foreground: ${tokens.colors.textMuted}; } }`}</style>
        {children}
      </body>
    </html>
  );
}
